apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-middlewares
  namespace: iam-system
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/component: ingress-controller
data:
  middlewares.yaml: |
    http:
      middlewares:
        strip-hsts:
          headers:
            customResponseHeaders:
              Strict-Transport-Security: ""
