apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: iam-system
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName patché par overlay (local-path / managed-csi / gp2)
