apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: infisical-store
  labels:
    app.kubernetes.io/name: infisical-store
    app.kubernetes.io/component: secret-store
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            secretRef:
              name: infisical-credentials
              namespace: external-secrets
              key: clientId
          clientSecret:
            secretRef:
              name: infisical-credentials
              namespace: external-secrets
              key: clientSecret
      secretsScope:
        projectSlug: swarm-iam-platform
        envSlug: prod-aws
        recursive: true
