apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Overlay Elastic Kubernetes Service (EKS)
# StorageClass : gp2 (EBS General Purpose SSD)

resources:
  - ../../../base
  - cluster-secret-store.yaml

patches:
  - path: patches/postgresql-storage.yaml
  - path: patches/redis-storage.yaml
  - path: patches/keycloak-hostname.yaml
